### ISSUE TITLE
Automatically add "hacktoberfest" to repository topic

### ISSUE THREAD

**Issue by TiagoDanin** [TiagoDanin/Hacktoberfest-Auto-Label#99]
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by renugasaraswathy** [comment]
Hi @TiagoDanin, I would like to work on this. Could you assign it to me? 

Thanks

**Comment by TiagoDanin** [comment]
Each time an issues to create check if the repo has the topic "hacktoberfest", if not:
Add new topic "hacktoberfest" via API (https://developer.github.com/v3/repos/#replace-all-repository-topics)
